[phases.setup]
nixPkgs = ['nodejs_18', 'curl']

[phases.install]
cmds = [
  'curl -fsSL https://get.pnpm.io/install.sh | sh -',
  'export PATH="$HOME/.local/share/pnpm:$PATH"',
  'pnpm install --no-strict-peer-dependencies'
]

[start]
cmd = 'export PATH="$HOME/.local/share/pnpm:$PATH" && pnpm start'