[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['corepack enable', 'corepack prepare pnpm@latest --activate', 'pnpm install --no-strict-peer-dependencies']

[start]
cmd = 'pnpm start'