[build]
builder = "NIXPACKS"
watchPatterns = ["apps/bot/**","packages/**","pnpm-lock.yaml","pnpm-workspace.yaml"]
[deploy]
startCommand = "pnpm -C apps/bot start:dev"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"