title = "allowlist for rotated tokens and examples"

[allowlist]
# Разрешаем ложные срабатывания в примерах/доках
paths = [
  '''\.env\.example''',
  '''/docs/.*\.md''',
  '''/apps/.*/\.env\.example''',
  '''\.claude/settings\.local\.json''',
  '''\.github/workflows/.*\.yml''',
  '''apps/.*/tsconfig\.build\.json''',
  '''apps/.*/package\.json''',
  '''pnpm-lock\.yaml'''
]

# Глобальные регексы для исключения тестовых значений
regexes = [
  '''test-token''',
  '''\btest\b''',
  '''1234567890abcdef''',
  '''@vitest/.*''',
  '''@playwright/test''',
  '''"test"''',
  '''safe-regex-test''',
  '''NODE_ENV=test''',
  '''TELEGRAM_BOT_TOKEN="test"'''
]

# Игнорируем конкретные коммиты, где секрет уже РОТИРОВАН  
commits = [
  "46f102a",  # fix: Add required environment variables for GitHub Actions CI  
  "05ac04d",  # feat: Complete CI/CD pipeline fixes and API improvements (squashed commit)
  "a08027e",  # Force Railway API service redeploy to apply Redis validation fixes
  "cb346e6"   # Update database connections: use Railway service references
]