title = "allowlist for rotated tokens and examples"

[allowlist]
# Разрешаем ложные срабатывания в примерах/доках
paths = [
  '''\.env\.example''',
  '''/docs/.*\.md''',
  '''/apps/.*/\.env\.example''',
  '''\.claude/settings\.local\.json''',
  '''\.github/workflows/.*\.yml''',
  '''apps/.*/tsconfig\.build\.json''',
  '''apps/.*/package\.json''',
  '''pnpm-lock\.yaml'''
]

# Глобальные регексы для исключения тестовых значений
regexes = [
  '''test-token''',
  '''\btest\b''',
  '''1234567890abcdef''',
  '''@vitest/.*''',
  '''@playwright/test''',
  '''"test"''',
  '''safe-regex-test''',
  '''NODE_ENV=test''',
  '''TELEGRAM_BOT_TOKEN="test"'''
]

# Правила редактирования для логирования (скрываем чувствительные данные)
[[rules]]
id = "redact-api-key"
description = "Redact API keys in logs"
regex = '''(api[_-]?key|token|password|secret)['"]?\s*[:=]\s*['"]?([A-Za-z0-9_-]{10,})['"]?'''
tags = ["redaction"]

[[rules]]
id = "redact-bearer-token"
description = "Redact Bearer tokens"
regex = '''\b[Bb]earer\s+([A-Za-z0-9_-]{20,})'''
tags = ["redaction"]

[[rules]]
id = "redact-database-url"
description = "Redact database connection strings"
regex = '''(postgres|mysql|mongodb)://([^:\s]+):([^@\s]+)@'''
tags = ["redaction"]

# Игнорируем конкретные коммиты, где секрет уже РОТИРОВАН  
commits = [
  "46f102a",  # fix: Add required environment variables for GitHub Actions CI  
  "05ac04d",  # feat: Complete CI/CD pipeline fixes and API improvements (squashed commit)
  "a08027e",  # Force Railway API service redeploy to apply Redis validation fixes
  "cb346e6"   # Update database connections: use Railway service references
]