[variables]
NIXPACKS_NO_DEFAULT_CACHE_DIRECTORIES = "1"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@9.0.0 --activate", 
  "pnpm i --frozen-lockfile || pnpm i"
]

[phases.build]
cmds = ["pnpm build --filter=@telegram-ios-academy/miniapp"]

[start]
cmd = "cd apps/miniapp && pnpm start"