[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'corepack enable',
  'corepack prepare pnpm@9.0.0 --activate',
  'cd ../..',
  'pnpm install'
]

[phases.build]
cmds = [
  'cd ../..',
  'pnpm build --filter=@telegram-ios-academy/miniapp'
]

[start]
cmd = 'cd apps/miniapp && pnpm start'