[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.toml"
watchPatterns = ["apps/miniapp/**","packages/ui/**","pnpm-lock.yaml","pnpm-workspace.yaml"]

[deploy]
healthcheckPath = "/health"
restartPolicyType = "always"

[environments.production.variables]
NODE_ENV = "production"
VITE_API_BASE_URL = "https://api-production-3e0e.up.railway.app"
