[build]
builder = "NIXPACKS"
buildCommand = "pnpm install --no-strict-peer-dependencies && pnpm build"
watchPatterns = ["apps/miniapp/**","packages/**","pnpm-lock.yaml","pnpm-workspace.yaml"]

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/"
restartPolicyType = "always"

[environments.production.variables]
NODE_ENV = "production"
VITE_API_BASE_URL = "https://api-production.up.railway.app"
