[build]
builder = "NIXPACKS"
watchPatterns = ["apps/miniapp/**","packages/**","pnpm-lock.yaml","pnpm-workspace.yaml"]
buildCommand = "npm install -g pnpm && pnpm build"

[deploy]
startCommand = "npm install -g pnpm && pnpm start"
healthcheckPath = "/"
restartPolicyType = "always"

[environments.production.variables]
NODE_ENV = "production"
VITE_API_BASE_URL = "https://api-production.up.railway.app"
