[build]
builder = "NIXPACKS"
watchPatterns = ["apps/miniapp/**","packages/**","pnpm-lock.yaml","pnpm-workspace.yaml","package.json"]

[deploy]
healthcheckPath = "/health"
restartPolicyType = "always"

[environments.production.variables]
NODE_ENV = "production"
VITE_API_BASE_URL = "https://api-production-3e0e.up.railway.app"
