[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'npm install -g pnpm@9.0.0',
  'pnpm install --frozen-lockfile'
]

[phases.build]
cmds = [
  'pnpm prisma generate',
  'pnpm build'
]

[start]
cmd = 'pnpm start'