[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'corepack enable',
  'corepack prepare pnpm@9.0.0 --activate',
  'pnpm install --frozen-lockfile'
]

[phases.build]
cmds = [
  'pnpm prisma generate',
  'pnpm build'
]

[start]
cmd = 'pnpm start'