[build]
builder = "NIXPACKS"
watchPatterns = ["apps/api/**","packages/**","pnpm-lock.yaml","pnpm-workspace.yaml"]
buildCommand = "corepack enable && corepack prepare pnpm@latest --activate && pnpm prisma generate && pnpm build"

[deploy]
startCommand = "corepack enable && corepack prepare pnpm@latest --activate && pnpm start"
healthcheckPath = "/api/health"
restartPolicyType = "always"

[environments.production.variables]
NODE_ENV = "production"
PORT = "3000"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
REDIS_URL = "${{Redis.REDIS_URL}}"
API_PUBLIC_ORIGIN = "${{RAILWAY_PUBLIC_DOMAIN}}"
ALLOWED_ORIGINS = "http://localhost:5173"
CSP_REPORT_ONLY = "0"
TELEGRAM_BOT_TOKEN = "PLACEHOLDER_REPLACE_IN_RAILWAY_UI"