[build]
builder = "NIXPACKS"
watchPatterns = ["apps/api/**","pnpm-lock.yaml","pnpm-workspace.yaml"]

[deploy]
healthcheckPath = "/api/health"
restartPolicyType = "always"

[environments.production.variables]
NODE_ENV = "production"
PORT = "3000"
DATABASE_URL = "PLACEHOLDER_ADD_POSTGRES_SERVICE_IN_RAILWAY"
REDIS_URL = "PLACEHOLDER_ADD_REDIS_SERVICE_IN_RAILWAY"
API_PUBLIC_ORIGIN = "https://${{RAILWAY_PUBLIC_DOMAIN}}"
ALLOWED_ORIGINS = "https://miniapp-production-9217.up.railway.app"
CSP_REPORT_ONLY = "0"