[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = ["apps/api/**","Dockerfile"]

[deploy]
healthcheckPath = "/api/health"
restartPolicyType = "always"

[environments.production.variables]
NODE_ENV = "production"
PORT = "3000"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
REDIS_URL = "${{Redis.REDIS_URL}}"
API_PUBLIC_ORIGIN = "${{RAILWAY_PUBLIC_DOMAIN}}"
ALLOWED_ORIGINS = "http://localhost:5173"
CSP_REPORT_ONLY = "0"
TELEGRAM_BOT_TOKEN = "PLACEHOLDER_REPLACE_IN_RAILWAY_UI"