name: CI

on:
  pull_request:
    branches: [develop, main, release/**, feature/**, hotfix/**]
  push:
    branches: [develop]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      root: ${{ steps.filter.outputs.root }}
      api: ${{ steps.filter.outputs.api }}
      miniapp: ${{ steps.filter.outputs.miniapp }}
      bot: ${{ steps.filter.outputs.bot }}
      packages: ${{ steps.filter.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            root:
              - 'pnpm-lock.yaml'
              - 'package.json'
              - 'turbo.json'
              - '.github/**'
            api:
              - 'apps/api/**'
            miniapp:
              - 'apps/miniapp/**'
            bot:
              - 'apps/bot/**'
            packages:
              - 'packages/**'

  build_typecheck:
    name: Build & Typecheck
    needs: changes
    if: |
      needs.changes.outputs.root == 'true' ||
      needs.changes.outputs.api == 'true' ||
      needs.changes.outputs.miniapp == 'true' ||
      needs.changes.outputs.bot == 'true' ||
      needs.changes.outputs.packages == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate Prisma Client (API)
        run: cd apps/api && pnpm prisma generate
      - name: Build all packages and applications
        run: pnpm -w build

  bundle_check:
    name: MiniApp bundle ≤ 220KB (gzip)
    needs: [changes, build_typecheck]
    if: needs.changes.outputs.miniapp == 'true' || needs.changes.outputs.packages == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build MiniApp for production
        run: pnpm -C apps/miniapp build
      - name: Assert bundle size ≤ 220KB gzipped
        run: |
          cat apps/miniapp/dist/assets/index-*.js | gzip | wc -c | awk '{
            kb=$1/1024; 
            printf("MiniApp gzipped bundle size: %.2f KB\n", kb); 
            if (kb > 220) { 
              printf("❌ Bundle too large! Must be ≤ 220KB\n"); 
              exit 1 
            } else {
              printf("✅ Bundle size within limits\n")
            }
          }'

  pact_contracts:
    name: Pact contracts (consumer/provider)
    needs: [changes, build_typecheck]
    if: needs.changes.outputs.api == 'true' || needs.changes.outputs.miniapp == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate Prisma Client (API)
        run: cd apps/api && pnpm prisma generate
      - name: Run Pact contract tests
        run: |
          echo "ℹ️ Pact contract tests not yet configured"
          # TODO: Configure Pact tests when ready
          # pnpm -w test:contracts || pnpm -w contracts:verify

  e2e_playwright:
    name: E2E Playwright (MiniApp)
    needs: [changes, build_typecheck]
    if: needs.changes.outputs.miniapp == 'true' || needs.changes.outputs.packages == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build MiniApp for testing
        run: pnpm -C apps/miniapp build
        env:
          VITE_API_BASE_URL: http://127.0.0.1:3000/api
      - name: Install Playwright with dependencies
        run: pnpm -C apps/miniapp exec playwright install --with-deps
      - name: Start preview server in background
        run: |
          cd apps/miniapp
          pnpm preview --port 5173 --host 0.0.0.0 & echo $! > preview.pid
          sleep 2
      - name: Wait for preview server
        run: |
          echo "Checking if preview server is running..."
          for i in {1..30}; do 
            echo "Attempt $i: Checking http://127.0.0.1:5173"
            if curl -sSf http://127.0.0.1:5173; then
              echo "✅ Preview server is running"
              break
            fi
            echo "Server not ready, waiting..."
            sleep 1
          done
          echo "Final check with verbose output:"
          curl -v http://127.0.0.1:5173 || echo "❌ Preview server failed to start"
      - name: Run Playwright E2E tests
        run: |
          echo "🧪 Starting E2E tests..."
          echo "Server should be available at http://127.0.0.1:5173"
          curl -I http://127.0.0.1:5173 || echo "⚠️ Server not responding before tests"
          cd apps/miniapp
          pnpm e2e
      - name: Stop preview server
        if: always()
        run: |
          cd apps/miniapp
          kill $(cat preview.pid) || true

  schemathesis_fuzz:
    name: API Schemathesis Fuzz
    needs: [changes, build_typecheck]
    if: needs.changes.outputs.api == 'true' || needs.changes.outputs.packages == 'true'
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - uses: pnpm/action-setup@v4
      - name: Install Python for Schemathesis
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Schemathesis
        run: pip install schemathesis
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate Prisma Client (API)
        run: cd apps/api && pnpm prisma generate
      - name: Build API
        run: pnpm -C apps/api build
      - name: Run database migrations
        run: |
          cd apps/api
          DATABASE_URL="postgresql://test:test@localhost:5432/test" pnpm prisma migrate deploy
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/test
      - name: Start API in background
        run: |
          cd apps/api
          DATABASE_URL="postgresql://test:test@localhost:5432/test" \
          REDIS_URL="redis://localhost:6379" \
          API_PUBLIC_ORIGIN="http://localhost:4010" \
          ALLOWED_ORIGINS="*" \
          CSP_REPORT_ONLY="1" \
          TELEGRAM_BOT_TOKEN="test-bot-token" \
          METRICS_TOKEN="test-schemathesis-token" \
          NODE_ENV=test \
          PORT=4010 \
          node dist/main.js & echo $! > ../../api.pid
      - name: Wait for API to be ready
        run: |
          echo "Waiting for API to start on port 4010..."
          for i in {1..30}; do 
            echo "Attempt $i: Checking API health..."
            if curl -sSf http://127.0.0.1:4010/api/health; then
              echo "✅ API health check passed"
              break
            fi
            echo "API not ready, waiting..."
            sleep 1
          done
          
          echo "Verifying OpenAPI endpoint availability..."
          curl -sSf http://127.0.0.1:4010/api/openapi.json | head -5 || echo "❌ OpenAPI endpoint not available"
          
          echo "API endpoints test complete"
      - name: Run Schemathesis fuzzing
        run: |
          schemathesis run http://127.0.0.1:4010/api/openapi.json \
            --url=http://127.0.0.1:4010 \
            --checks=all \
            --request-timeout=5 \
            --wait-for-schema=30 \
            -H "Authorization: Bearer test" \
            -H "Idempotency-Key: ci-$(date +%s)" \
            --phases=examples,fuzzing,stateful \
            --max-examples=50
      - name: Cleanup API process
        if: always()
        run: kill $(cat api.pid) || true

  security_audit:
    name: Security Audit (pnpm audit --audit-level high)
    needs: changes
    if: |
      needs.changes.outputs.root == 'true' ||
      needs.changes.outputs.api == 'true' ||
      needs.changes.outputs.miniapp == 'true' ||
      needs.changes.outputs.bot == 'true' ||
      needs.changes.outputs.packages == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run security audit
        run: pnpm audit --audit-level high

  gitleaks:
    name: gitleaks secret scanning
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-path: .gitleaks.toml
          args: "--verbose"