name: Storybook

on:
  pull_request:
    branches: [develop, main, feature/**]
  push:
    branches: [develop]

concurrency:
  group: storybook-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      ui: ${{ steps.filter.outputs.ui }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ui:
              - 'packages/ui/**'
              - 'apps/miniapp/**'

  build_storybook:
    name: Build Storybook static site
    needs: changes
    if: needs.changes.outputs.ui == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Storybook static site
        run: pnpm -C packages/ui build-storybook
      - name: Upload Storybook artifacts
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: packages/ui/storybook-static
          retention-days: 7

  chromatic_visual_tests:
    name: Chromatic visual regression tests
    needs: changes
    if: needs.changes.outputs.ui == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - run: corepack enable
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Chromatic visual tests
        run: |
          if [ -n "$CHROMATIC_PROJECT_TOKEN" ]; then
            pnpm -C packages/ui chromatic
          else
            echo "⚠️ CHROMATIC_PROJECT_TOKEN not set, skipping visual tests"
          fi
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  accessibility_tests:
    name: Accessibility tests with axe
    needs: changes
    if: needs.changes.outputs.ui == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run accessibility tests
        run: pnpm -C packages/ui test:a11y || echo "A11y tests not configured yet"